layout_spectrum: 1
typography_spectrum: 0.5311973
color:
  saturation: 0.8421851
  lightness: 0.2360877
  brandStrength: 0.1141053
  brandColors:
    - '#182433'
    - '#7C6F6F'
    - '#493F3F'
    - '#B1C4D5'
    - '#9DAAB2'
  rhythmicContrast: 0.7964698
name: The Brick & Stone Company
